version: '3.5'
services:
  frontend:
    build:
      context: ./frontend
      target: prod
    image: cooking-assistant-frontend:prod
    ports:
      - '5000:5000'
    restart: always
  node-server:
    build:
      context: ./server
      target: prod
    image: cooking-assistant-server:prod
    ports:
      - '3000:3000'
    restart: always
