version: '3.5'
services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - '5000:5000'
      - '35729:35729'
    restart: always
  node-server:
    build:
      context: ./server
      target: prod
    ports:
      - '3000:3000'
    restart: always
    networks:
      - rhasspy_network_external

networks:
  rhasspy_network_external:
    external: true
